spring:
  application:
    name: boombeene
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boombeene?serverTimezone=Asia/Seoul
    username: admin
    password: topsecret
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  session:
    store-type: redis
    timeout: 30m

kakao:
  local:
    base-url: https://dapi.kakao.com
    api-key: ${KAKAO_API_KEY}

server:
  servlet:
    session:
      cookie:
        same-site: lax

kind: Application
