spring:
  application:
    name: boombeene
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boombeene?serverTimezone=Asia/Seoul
    username: admin
    password: topsecret
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  session:
    store-type: redis
    timeout: 30m

kind: Application
