spring:
  application:
    name: boombeene
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://mysql:3306/boombeene?serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  session:
    store-type: redis
    timeout: 30m

kakao:
  local:
    base-url: https://dapi.kakao.com
    api-key: ${KAKAO_API_KEY}
    connect-timeout: 2s
    read-timeout: 5s

cors:
  allowed-origins: https://boombeene.tomash.me

server:
  servlet:
    session:
      cookie:
        same-site: lax
