spring:
  application:
    name: boombeene
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boombeene?serverTimezone=Asia/Seoul
    username: admin
    password: topsecret
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      format_sql: true
      use_sql_comments: true
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  session:
    store-type: redis
    timeout: 30m

logging:
  level:
    org.hibernate.type: trace

kakao:
  local:
    base-url: https://dapi.kakao.com
    api-key: ${KAKAO_API_KEY}
    connect-timeout: 2s
    read-timeout: 5s

cors:
  allowed-origins: http://localhost:5173

server:
  servlet:
    session:
      cookie:
        same-site: lax

kind: Application
